steps:

# Install dependencies
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]

# Run unit tests
- name: python
  entrypoint: python
  args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"] 

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-gcp:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello-gcp:$COMMIT_SHA']
# Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/IMAGE', '--region', 'SERVICE_REGION']


# # Step to create or update a Cloud Scheduler job
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       # Variables
#       #SCHEDULER_JOB_NAME="hello-gcp-scheduler-job"
#       SCHEDULE="$_SCHEDULE"
            
#       # Check if the job exists
#       if gcloud scheduler jobs describe "hello-gcp-scheduler-job" --quiet; then
#         echo "Updating existing scheduler job..."
#         gcloud scheduler jobs update http \
#           "hello-gcp-scheduler-job" \
#           --schedule "$_SCHEDULE" \
#           --time-zone "$_TIMEZONE" \
#           --uri $_TARGET_URL \
#           --http-method "$_HTTP_METHOD" \
#           --location us-central1 \
#           --oauth-service-account-email "$_SERVICE_ACCOUNT"
#       else
#         echo "Creating new scheduler job... $_SCHEDULE  $SERVICE_ACCOUNT"
#         gcloud scheduler jobs create http \
#           "hello-gcp-scheduler-job" \
#           --schedule "$_SCHEDULE" \
#           --time-zone "$_TIMEZONE" \
#           --uri "$_TARGET_URL" \
#           --http-method "$_HTTP_METHOD" \
#           --location us-central1 \
#           --oauth-service-account-email "$_SERVICE_ACCOUNT"
#       fi


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud'
  - 'deployment-manager'
  - 'deployments'
  - 'create'
  - 'my-deployment'
  - '--config=deploy/scheduler-job.yaml'

timeout: '600s'

substitutions:
  _TARGET_URL: https://us-central1-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/the-training/jobs/deploy-run-job-dev:run
  _SCHEDULE: '* * * * *'
  _TIMEZONE: 'UTC'
  _HTTP_METHOD: 'POST'
  _SERVICE_ACCOUNT: 'diego-sa@the-training.iam.gserviceaccount.com'

images:
- gcr.io/$PROJECT_ID/hello-gcp:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
