steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/the-training/IMAGE', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/the-training/IMAGE']
# Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'SERVICE_NAME', '--image', 'gcr.io/the-training/IMAGE', '--region', 'SERVICE_REGION']
images:
- gcr.io/the-training/IMAGE

options:
  logging: CLOUD_LOGGING_ONLY
