apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-delivery-pipeline
description: main application pipeline
serialPipeline:
  stages:
  - targetId: demo-target-run-dev
    profiles: [dev]
  - targetId: demo-target-run-prod
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: demo-target-run-dev
description: Cloud Run Development service
run:
  location: projects/${PROJECT}/locations/${REGION}
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: demo-target-run-prod
description: Cloud Run Production service
run:
  location: projects/${PROJECT}/locations/${REGION}