apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: deploy-run-job-dev
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - image: gcr.io/$PROJECT_ID/hello-gcp