apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: deploy-run-job-prod
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: ${SERVICE_ACCOUNT}
          containers:          
          - image: job-image
            env:
              - name: DEMO_URI
                value: "https://demo.com"
              - name: DB_CREDENTIALS
                valueFrom:
                  secretKeyRef:
                    key: latest
                    name: demo-database-credentials