apiVersion: skaffold/v4beta7
kind: Config
metadata: 
  name: deploy-run-quickstart
profiles:
- name: dev
  manifests:
    rawYaml:
    - run-job-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - run-job-prod.yaml
deploy:
  cloudrun: {}