apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: deploy-run-quickstart
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - /workspace/source/deploy/prod.yaml
deploy:
  cloudrun: {}
  logs:
    prefix: container